version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 619942913628.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI1=619942913628.dkr.ecr.us-east-1.amazonaws.com/gaia-runner
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t gaia-runner:v1 .
      - docker tag gaia-runner:v1 $REPOSITORY_URI1:runner
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI1:runner
      - printf '[{"name":"gaia-runner","imageUri":"619942913628.dkr.ecr.us-east-1.amazonaws.com/gaia-runner:runner"}]' >> imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
